name: e_instru
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.2
  http: ^1.6.0
  sqflite: ^2.4.2+1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1

# Configuration de l'icône de l'application
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

# Configuration de l'écran de démarrage (Splash Screen)
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon/splash_logo.png"

  # Prise en charge d'Android 12 et versions ultérieures
  android_12:
    image: "assets/icon/splash_logo.png"
    color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/